docs/nistvol8-2.md
=> Update nistvol8-2.md - typo

docs/nistvol8-2.md
Version 3 of the documents won't have a section 1.5 (Future Work)
=> Update nistvol8-2.md - Delete 1.5 reference

docs/nistvol8-2.md
Standardizing marking of first level headers.
=> Update nistvol8-2.md - header standardization 

docs/nistvol8-2.md
The fourth bullet needs a "title" (i.e., few words at the beginning to summarize the bullet) like the other bullets have.
=> Authentication edits

docs/nistvol8-2.md
does the work here reflect the stage 3 goal? or should we say that "this document contains the results of the nbd-pwg interfaces subgroup work on the stage 2 goal"?
=> More Exec Summary edits

docs/nistvol8-2.md
Is version 3 still the last planned version of this document? If so, the "Future Work on this Volume" section should be deleted.
=> Delete Future Work section?

docs/nistvol8-2.md
This paragraph seemed to speak more to the report structure instead of the report production.
=> Move paragraph to Report structure

docs/nistvol8-2.md
Are the new versions still being tagged?
=> Version Management edits

docs/nistvol8-2.md
Is https://github.com/cloudmesh-community/nist/tree/master/services the correct URL that needs to be added to the text?
=> Specification edits

docs/nistvol8-2.md
Is this still true? Was there discussion of putting the examples in another document? Also, are we still asking for contributions?
=> Design by Example edits

docs/nistvol8-2.md
We might want to include a sentence or two about Phase 3 work. If we don't talk about Phase 3 work, then the partial sentence "Phase 3 work, which built upon the groundwork developed during Phase 2, included..." should be deleted.
=> Report Production edits

docs/nistvol8-2.md
The figure reference in the paragraph "The DATA arrows in ..." refers to the reference architecture. "Figure 2" must have been a left over from copied text.
=> Figure reference

spec/timestamp.yaml
Not sure if Data was intended to be singular or plural here (I assumed singular) but "needs/need" and "it has/they have" should both agree with "data". Please modify if "data is plural.
=> Timestamp edit

docs/nistvol8-2.md
Replaced text about the different versions of the volumes with the new standardized text that will be added to all volumes. New text is placed in the Executive Summary and Section 1.1
=> Add standard text about versions to Exec Summ and S1.1

docs/nistvol8-2.md
One public comment requested removing "remarkable" from section 1.1
=> Remove "remarkable" Sec 1.1

docs/nistvol8-2.md
This is the text to go with the new figure: NIST Big Data Interoperability Framework (NBDIF) Documents Navigation Diagram
=> Added text for new figure

docs/nistvol8-2.md
Edited the text introducing the two figures to differentiate them and explain the figures somewhat.
=> Figure text edits

docs/nistvol8-2.md
Proposed changes to Section 4.0 text
=> Proposed changes Sec 4

docs/nistvol8-2.md
The Interface group is under the Reference Architecture group.
=> Ackn change 1

docs/nistvol8-2.md
Minor edits to Executive summary, including reversing order of the stages (per comment from Wo).
=> Executive Summary update
